// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: micronf_agent.proto

#ifndef PROTOBUF_micronf_5fagent_2eproto__INCLUDED
#define PROTOBUF_micronf_5fagent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rpc_agent {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_micronf_5fagent_2eproto();
void protobuf_AssignDesc_micronf_5fagent_2eproto();
void protobuf_ShutdownFile_micronf_5fagent_2eproto();

class CreateRingRequest;
class DeployConfig;
class Errno;

// ===================================================================

class CreateRingRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpc_agent.CreateRingRequest) */ {
 public:
  CreateRingRequest();
  virtual ~CreateRingRequest();

  CreateRingRequest(const CreateRingRequest& from);

  inline CreateRingRequest& operator=(const CreateRingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateRingRequest& default_instance();

  void Swap(CreateRingRequest* other);

  // implements Message ----------------------------------------------

  inline CreateRingRequest* New() const { return New(NULL); }

  CreateRingRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateRingRequest& from);
  void MergeFrom(const CreateRingRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreateRingRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:rpc_agent.CreateRingRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_micronf_5fagent_2eproto();
  friend void protobuf_AssignDesc_micronf_5fagent_2eproto();
  friend void protobuf_ShutdownFile_micronf_5fagent_2eproto();

  void InitAsDefaultInstance();
  static CreateRingRequest* default_instance_;
};
// -------------------------------------------------------------------

class Errno : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpc_agent.Errno) */ {
 public:
  Errno();
  virtual ~Errno();

  Errno(const Errno& from);

  inline Errno& operator=(const Errno& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Errno& default_instance();

  void Swap(Errno* other);

  // implements Message ----------------------------------------------

  inline Errno* New() const { return New(NULL); }

  Errno* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Errno& from);
  void MergeFrom(const Errno& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Errno* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::google::protobuf::int32 err() const;
  void set_err(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rpc_agent.Errno)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_micronf_5fagent_2eproto();
  friend void protobuf_AssignDesc_micronf_5fagent_2eproto();
  friend void protobuf_ShutdownFile_micronf_5fagent_2eproto();

  void InitAsDefaultInstance();
  static Errno* default_instance_;
};
// -------------------------------------------------------------------

class DeployConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpc_agent.DeployConfig) */ {
 public:
  DeployConfig();
  virtual ~DeployConfig();

  DeployConfig(const DeployConfig& from);

  inline DeployConfig& operator=(const DeployConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeployConfig& default_instance();

  void Swap(DeployConfig* other);

  // implements Message ----------------------------------------------

  inline DeployConfig* New() const { return New(NULL); }

  DeployConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeployConfig& from);
  void MergeFrom(const DeployConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeployConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string config = 1;
  void clear_config();
  static const int kConfigFieldNumber = 1;
  const ::std::string& config() const;
  void set_config(const ::std::string& value);
  void set_config(const char* value);
  void set_config(const char* value, size_t size);
  ::std::string* mutable_config();
  ::std::string* release_config();
  void set_allocated_config(::std::string* config);

  // @@protoc_insertion_point(class_scope:rpc_agent.DeployConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr config_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_micronf_5fagent_2eproto();
  friend void protobuf_AssignDesc_micronf_5fagent_2eproto();
  friend void protobuf_ShutdownFile_micronf_5fagent_2eproto();

  void InitAsDefaultInstance();
  static DeployConfig* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CreateRingRequest

// optional string name = 1;
inline void CreateRingRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRingRequest::name() const {
  // @@protoc_insertion_point(field_get:rpc_agent.CreateRingRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRingRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpc_agent.CreateRingRequest.name)
}
inline void CreateRingRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpc_agent.CreateRingRequest.name)
}
inline void CreateRingRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpc_agent.CreateRingRequest.name)
}
inline ::std::string* CreateRingRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:rpc_agent.CreateRingRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRingRequest::release_name() {
  // @@protoc_insertion_point(field_release:rpc_agent.CreateRingRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRingRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:rpc_agent.CreateRingRequest.name)
}

// -------------------------------------------------------------------

// Errno

// optional int32 err = 1;
inline void Errno::clear_err() {
  err_ = 0;
}
inline ::google::protobuf::int32 Errno::err() const {
  // @@protoc_insertion_point(field_get:rpc_agent.Errno.err)
  return err_;
}
inline void Errno::set_err(::google::protobuf::int32 value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:rpc_agent.Errno.err)
}

// -------------------------------------------------------------------

// DeployConfig

// optional string config = 1;
inline void DeployConfig::clear_config() {
  config_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeployConfig::config() const {
  // @@protoc_insertion_point(field_get:rpc_agent.DeployConfig.config)
  return config_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeployConfig::set_config(const ::std::string& value) {
  
  config_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpc_agent.DeployConfig.config)
}
inline void DeployConfig::set_config(const char* value) {
  
  config_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpc_agent.DeployConfig.config)
}
inline void DeployConfig::set_config(const char* value, size_t size) {
  
  config_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpc_agent.DeployConfig.config)
}
inline ::std::string* DeployConfig::mutable_config() {
  
  // @@protoc_insertion_point(field_mutable:rpc_agent.DeployConfig.config)
  return config_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeployConfig::release_config() {
  // @@protoc_insertion_point(field_release:rpc_agent.DeployConfig.config)
  
  return config_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeployConfig::set_allocated_config(::std::string* config) {
  if (config != NULL) {
    
  } else {
    
  }
  config_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), config);
  // @@protoc_insertion_point(field_set_allocated:rpc_agent.DeployConfig.config)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc_agent

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_micronf_5fagent_2eproto__INCLUDED
